insert into games ( id, title, platform, score, genre, editors_choice) values ('1','LittleBigPlanet PS Vita','PlayStation Vita',9,'Platformer','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('2','LittleBigPlanet PS Vita - Marvel Super Hero Edition','PlayStation Vita',9,'Platformer','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('3','Splice: Tree of Life','iPad',8.5,'Puzzle','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('4','NHL 13','Xbox 360',8.5,'Sports','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('5','NHL 13','PlayStation 3',8.5,'Sports','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('6','Total War Battles: Shogun','Macintosh',7,'Strategy','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('7','Double Dragon: Neon','Xbox 360',3,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('8','Guild Wars 2','PC',9,'RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('9','Double Dragon: Neon','PlayStation 3',3,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('10','Total War Battles: Shogun','PC',7,'Strategy','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('11','Tekken Tag Tournament 2','PlayStation 3',7.5,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('12','Tekken Tag Tournament 2','Xbox 360',7.5,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('13','Wild Blood','iPhone',7,'','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('14','Mark of the Ninja','Xbox 360',9,'Action, Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('15','Mark of the Ninja','PC',9,'Action, Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('16','Home: A Unique Horror Adventure','Macintosh',6.5,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('17','Home: A Unique Horror Adventure','PC',6.5,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('18','Avengers Initiative','iPhone',8,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('19','Way of the Samurai 4','PlayStation 3',5.5,'Action, Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('20','JoJo’s Bizarre Adventure HD','Xbox 360',7,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('21','JoJo’s Bizarre Adventure HD','PlayStation 3',7,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('22','Mass Effect 3: Leviathan','Xbox 360',7.5,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('23','Mass Effect 3: Leviathan','PlayStation 3',7.5,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('24','Mass Effect 3: Leviathan','PC',7.5,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('25','Dark Souls (Prepare to Die Edition)','PC',9,'Action, RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('26','Symphony','PC',7,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('27','Bastion','iPad',9,'Action, RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('28','Tom Clancy’s Ghost Recon Phantoms','PC',7.5,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('29','Thirty Flights of Loving','PC',8,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('30','Legasista','PlayStation 3',6.5,'Action, RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('31','The Walking Dead: The Game - Episode 3: Long Road Ahead','Macintosh',9,'Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('32','World of Warcraft: Mists of Pandaria','PC',8.7,'RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('33','Hell Yeah! Wrath of the Dead Rabbit','PlayStation 3',4.9,'Platformer','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('34','Pokemon White Version 2','Nintendo DS',9.6,'RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('35','War of the Roses','PC',7.3,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('36','Pokemon Black Version 2','Nintendo DS',9.6,'RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('37','Drakerider','iPhone',6.5,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('38','The Walking Dead: The Game - Episode 3: Long Road Ahead','Xbox 360',9,'Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('39','The Walking Dead: The Game - Episode 3: Long Road Ahead','PC',9,'Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('40','The Walking Dead: The Game - Episode 3: Long Road Ahead','PlayStation 3',9,'Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('41','Rock Band Blitz','Xbox 360',8.5,'Music','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('42','Counter-Strike: Global Offensive','Macintosh',8,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('43','Worms Revolution','PlayStation 3',8.5,'Strategy','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('44','Worms Revolution','PC',8.5,'Strategy','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('45','Worms Revolution','Xbox 360',8.5,'Strategy','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('46','Bad Piggies','iPhone',9.2,'Action','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('47','Resident Evil 6','PlayStation 3',7.9,'Action, Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('48','Resident Evil 6','Xbox 360',7.9,'Action, Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('49','Shad`O`','PC',7,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('50','Demon’s Score','iPhone',6.9,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('51','NBA 2K13','Xbox 360',9.1,'Sports','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('52','Counter-Strike: Global Offensive','PC',8,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('53','The World Ends with You: Solo Remix','iPad',9.5,'RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('54','Counter-Strike: Global Offensive','PlayStation 3',8,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('55','The World Ends with You: Solo Remix','iPhone',9.5,'RPG','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('56','Counter-Strike: Global Offensive','Xbox 360',8,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('57','Madden NFL 13','PlayStation Vita',6,'Sports','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('58','Madden NFL 13','PlayStation 3',9,'Sports','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('59','Madden NFL 13','Xbox 360',9,'Sports','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('60','Hoodwink','PC',2.5,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('61','NBA 2K13','PlayStation 3',9.1,'Sports','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('62','NBA 2K13','PC',9.1,'Sports','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('63','Lili: Child of Geos','iPhone',7,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('64','Marvel vs. Capcom Origins','Xbox 360',8.2,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('65','Marvel vs. Capcom Origins','PlayStation 3',8.2,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('66','Dead or Alive 5','PlayStation 3',8.8,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('67','Dead or Alive 5','Xbox 360',8.8,'Fighting','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('68','Medal of Honor Warfighter','PC',4,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('69','Professor Layton and the Miracle Mask','Nintendo 3DS',8.7,'Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('70','Hotline Miami','PC',8.8,'Action','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('71','Edna & Harvey: Harvey’s New Eyes','PC',6,'Adventure','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('72','Medal of Honor Warfighter','PlayStation 3',4,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('73','Medal of Honor Warfighter','Xbox 360',4,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('74','Transformers: Fall of Cybertron','Xbox 360',8.5,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('75','Transformers: Fall of Cybertron','PlayStation 3',8.5,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('76','Hero Academy','PC',9,'Board','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('77','Hero Academy','iPhone',9,'Strategy','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('78','Puzzle Craft','iPhone',9,'Puzzle','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('79','Realms Of Ancient War','Xbox 360',5.5,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('80','Realms Of Ancient War','PlayStation 3',5.5,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('81','Anomaly: Warzone Earth','PlayStation 3',8.2,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('82','Darksiders II','PC',7.5,'Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('83','Left 4 Dead 2: Cold Stream','Macintosh',7,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('84','Left 4 Dead 2: Cold Stream','PC',7,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('85','Puzzle Craft','Android',9,'Puzzle','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('86','Left 4 Dead 2: Cold Stream','Xbox 360',7,'Shooter','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('87','Horn','iPhone',9,'Action, Adventure','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('88','Forza Horizon','Xbox 360',9,'Racing','Y');
insert into games ( id, title, platform, score, genre, editors_choice) values ('89','FIFA Soccer 13','PlayStation Vita',4,'Sports','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('90','Mugen Souls','PlayStation 3',3.9,'Strategy, RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('91','Crazy Taxi','iPhone',7.1,'Racing, Action','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('92','New Little King’s Story','PlayStation Vita',5.8,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('93','Fable: The Journey','Xbox 360',7.2,'Action, RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('94','The Lord of the Rings Online: Riders of Rohan','PC',8.3,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('95','Doom 3: BFG Edition','Xbox 360',7.6,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('96','Rugby League Live 2','Xbox 360',6,'Sports','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('97','Rugby League Live 2','PlayStation 3',6,'Sports','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('98','Doom 3: BFG Edition','PlayStation 3',7.6,'RPG','N');
insert into games ( id, title, platform, score, genre, editors_choice) values ('99','Punch Quest','iPhone',9.3,'Action','Y');
